/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.app.mvictor.view;

import br.app.mvictor.dao.AlunoDAO;
import br.app.mvictor.service.ModeloTabela;
import br.app.mvictor.service.Validar;
import br.app.mvictor.entidade.Aluno;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JTextField;


/**
 *
 * @author mvictor
 */
public class Tela extends javax.swing.JFrame {

    private ModeloTabela modelo = new ModeloTabela();
    private AlunoDAO dao = new AlunoDAO();
    /**
     * Creates new form tela
     */
    public Tela() {
        initComponents();
        //setando o modelo de tabela criado.
        tbl.setModel(modelo);
       
        //configurando o tamanho das colunas da tabela.
        //coluna matricula
        this.tbl.getColumnModel().getColumn(0).setPreferredWidth(70);
        this.tbl.getColumnModel().getColumn(0).setMinWidth(70);
        this.tbl.getColumnModel().getColumn(0).setMaxWidth(70);
        //coluna nome
        this.tbl.getColumnModel().getColumn(1).setPreferredWidth(200);
        this.tbl.getColumnModel().getColumn(1).setMinWidth(200);
        this.tbl.getColumnModel().getColumn(1).setMaxWidth(200);
        //coluna curso
        this.tbl.getColumnModel().getColumn(2).setPreferredWidth(100);
        this.tbl.getColumnModel().getColumn(2).setMinWidth(100);
        this.tbl.getColumnModel().getColumn(2).setMaxWidth(100);
        
        //coluna notas
        //nota 1
        this.tbl.getColumnModel().getColumn(3).setPreferredWidth(60);
        this.tbl.getColumnModel().getColumn(3).setMinWidth(60);
        this.tbl.getColumnModel().getColumn(3).setMaxWidth(60);
        //nota 2
        this.tbl.getColumnModel().getColumn(4).setPreferredWidth(60);
        this.tbl.getColumnModel().getColumn(4).setMinWidth(60);
        this.tbl.getColumnModel().getColumn(4).setMaxWidth(60);
        //nota 3
        this.tbl.getColumnModel().getColumn(5).setPreferredWidth(60);
        this.tbl.getColumnModel().getColumn(5).setMinWidth(60);
        this.tbl.getColumnModel().getColumn(5).setMaxWidth(60);
        //nota 4
        this.tbl.getColumnModel().getColumn(6).setPreferredWidth(60);
        this.tbl.getColumnModel().getColumn(6).setMinWidth(60);
        this.tbl.getColumnModel().getColumn(6).setMaxWidth(60);
        
        this.modelo.atualizarListaTabela(this.dao.findAll());
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        lbl_nome = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        lbl_matricula = new javax.swing.JLabel();
        lbl_curso = new javax.swing.JLabel();
        txt_curso = new javax.swing.JTextField();
        lbl_notas = new javax.swing.JLabel();
        spin_nota1 = new javax.swing.JSpinner();
        spin_nota2 = new javax.swing.JSpinner();
        spin_nota3 = new javax.swing.JSpinner();
        spin_nota4 = new javax.swing.JSpinner();
        btn_cadastrar = new javax.swing.JButton();
        btn_remover = new javax.swing.JButton();
        btn_listar = new javax.swing.JButton();
        spin_matricula = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        lbl_pesquisar = new javax.swing.JLabel();
        btn_buscar = new javax.swing.JButton();
        spin_buscar = new javax.swing.JSpinner();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        menu_item = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Tela de Cadastro", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        lbl_nome.setText("Nome");

        lbl_matricula.setText("Mat.");

        lbl_curso.setText("Curso");

        lbl_notas.setText("Notas");

        spin_nota1.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), Float.valueOf(10.0f), Float.valueOf(0.1f)));

        spin_nota2.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), Float.valueOf(10.0f), Float.valueOf(0.1f)));

        spin_nota3.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), Float.valueOf(10.0f), Float.valueOf(0.1f)));

        spin_nota4.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), Float.valueOf(10.0f), Float.valueOf(0.1f)));

        btn_cadastrar.setText("Cadastrar");
        btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarActionPerformed(evt);
            }
        });

        btn_remover.setText("Remover");
        btn_remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removerActionPerformed(evt);
            }
        });

        btn_listar.setText("Atual.Listar");
        btn_listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_listarActionPerformed(evt);
            }
        });

        spin_matricula.setModel(new javax.swing.SpinnerNumberModel(Long.valueOf(1000L), Long.valueOf(1000L), Long.valueOf(9000L), Long.valueOf(1L)));

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_nome)
                            .addComponent(lbl_matricula))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                                .addComponent(lbl_curso)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_curso, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(lbl_notas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spin_matricula, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(btn_cadastrar)
                                .addGap(35, 35, 35)
                                .addComponent(btn_remover)
                                .addGap(33, 33, 33)
                                .addComponent(btn_listar))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(spin_nota1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(spin_nota2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(spin_nota3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(spin_nota4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nome)
                    .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_matricula)
                    .addComponent(lbl_curso)
                    .addComponent(txt_curso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spin_matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_notas)
                    .addComponent(spin_nota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spin_nota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spin_nota3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spin_nota4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cadastrar)
                    .addComponent(btn_remover)
                    .addComponent(btn_listar))
                .addContainerGap())
        );

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "nome", "null", "null"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbl.setSurrendersFocusOnKeystroke(true);
        tbl.getTableHeader().setResizingAllowed(false);
        tbl.getTableHeader().setReorderingAllowed(false);
        tbl.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                tblAncestorRemoved(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);
        if (tbl.getColumnModel().getColumnCount() > 0) {
            tbl.getColumnModel().getColumn(0).setResizable(false);
            tbl.getColumnModel().getColumn(1).setResizable(false);
            tbl.getColumnModel().getColumn(2).setResizable(false);
        }

        lbl_pesquisar.setText("Pesquisar Matricula");

        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        spin_buscar.setModel(new javax.swing.SpinnerNumberModel(Long.valueOf(1000L), Long.valueOf(1000L), Long.valueOf(9000L), Long.valueOf(1L)));

        menu.setText("Tela Principal");

        menu_item.setText("Home");
        menu_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_itemActionPerformed(evt);
            }
        });
        menu.add(menu_item);

        jMenuBar1.add(menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_pesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spin_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_pesquisar)
                    .addComponent(btn_buscar)
                    .addComponent(spin_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed
        // TODO add your handling code here:
        
        if(Validar.isEmpty(txt_nome))
        {
            JOptionPane.showMessageDialog(null, "Campo [nome do curso] está vázio, porfavor preecha!");
        }
        
        else if(Validar.isEmpty(txt_curso))
        {
            JOptionPane.showMessageDialog(null, "Campo [nome do curso] está vázio, porfavor preecha!");
        }
        else{
            Aluno a = new Aluno();
            //dados do aluno.
            long numero_matricula  = (long) spin_matricula.getValue();
            
            if(dao.verificarId((long)this.spin_matricula.getValue()))
            {
                JOptionPane.showMessageDialog(null, "Esse número de matricula já consta no sistema!");
            }
            else if(Validar.isNotLetters(txt_curso) == false)
            {
                JOptionPane.showMessageDialog(null, "Nome de curso inválido, tente novamente");
            }
            else if(Validar.isNotLetters(txt_nome) == false)
            {
                JOptionPane.showMessageDialog(null, "Nome de aluno inválido, tente novamente");
            }
            else{
                a.setMatricula(numero_matricula);
                a.setNome(txt_nome.getText());
                a.setCurso(txt_curso.getText());
                a.setNota1((float)spin_nota1.getValue());
                a.setNota2((float)spin_nota2.getValue());
                a.setNota3((float)spin_nota3.getValue());
                a.setNota4((float)spin_nota4.getValue());
                dao.inserir(a);
                modelo.atualizarListaTabela(dao.findAll());
                JOptionPane.showMessageDialog(null, "Aluno cadastrado com sucesso...");
            }
            
        }
    }//GEN-LAST:event_btn_cadastrarActionPerformed

    private void tblAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblAncestorRemoved
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_tblAncestorRemoved

    private void btn_listarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_listarActionPerformed
        // TODO add your handling code here:
        
        this.modelo.atualizarListaTabela(this.dao.findAll());
    }//GEN-LAST:event_btn_listarActionPerformed

    private void btn_removerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removerActionPerformed
        // TODO add your handling code here:
        Object[] opcoes =  {"Não", "Sim"};
        int resultado = JOptionPane.showOptionDialog(null, "Deseja deletar esse registro?", "Aviso",JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, opcoes, opcoes[1]);
        
        switch(resultado)
        {
            case 1:
                int posicao = this.tbl.getSelectedRow();
                if(posicao == -1)
                {
                    JOptionPane.showMessageDialog(null,"É necessário selecionar uma linha, para remover!");
                }
                else{
                    Aluno a = new Aluno();
                    a.setMatricula((long) this.tbl.getValueAt(this.tbl.getSelectedRow(), 0));
                    this.modelo.removerLinhaDaTabela(posicao);
                    this.dao.remover(a);
                    JOptionPane.showMessageDialog(null,"Removido com sucesso...");
                    this.modelo.atualizarListaTabela(this.dao.findAll());
                }
                
            break;
            
        }
    }//GEN-LAST:event_btn_removerActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        // TODO add your handling code here:
       
        if(dao.verificarId((long)this.spin_buscar.getValue()) == false)
        {
            JOptionPane.showMessageDialog(this, "Matricula não registrada!");
            modelo.atualizarListaTabela(dao.findAll());
        }
        else{
            modelo.limparTabela();
            Aluno a = new Aluno();
            a = dao.getById((long)spin_buscar.getValue());
            modelo.adicionarNovoElementoNaLinhaDaTabela(a);
            JOptionPane.showMessageDialog(this, "Matricula Encontrada!");
        }
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() == 2)
        {
            Aluno a = new Aluno();
            a.setMatricula((long)this.tbl.getValueAt(this.tbl.getSelectedRow(), 0));
            a.setNome((String)this.tbl.getValueAt(this.tbl.getSelectedRow(), 1));
            a.setCurso((String)this.tbl.getValueAt(this.tbl.getSelectedRow(),2));
            a.setNota1((float) this.tbl.getValueAt(this.tbl.getSelectedRow(), 3));
            a.setNota2((float) this.tbl.getValueAt(this.tbl.getSelectedRow(), 4));
            a.setNota3((float) this.tbl.getValueAt(this.tbl.getSelectedRow(), 5));
            a.setNota4((float) this.tbl.getValueAt(this.tbl.getSelectedRow(), 6));
            Editar editar = new Editar();
            editar.exportarDados(a);
            editar.setVisible(true);
            this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
            this.dispose();
            
        }
    }//GEN-LAST:event_tblMouseClicked

    private void menu_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_itemActionPerformed
        // TODO add your handling code here:
        Principal p = new Principal();
        p.setVisible(true);
        this.setDefaultCloseOperation(Tela.EXIT_ON_CLOSE);
        this.dispose();
        
    }//GEN-LAST:event_menu_itemActionPerformed
    
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JButton btn_listar;
    private javax.swing.JButton btn_remover;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_curso;
    private javax.swing.JLabel lbl_matricula;
    private javax.swing.JLabel lbl_nome;
    private javax.swing.JLabel lbl_notas;
    private javax.swing.JLabel lbl_pesquisar;
    private javax.swing.JMenu menu;
    private javax.swing.JMenuItem menu_item;
    private javax.swing.JPanel panel;
    private javax.swing.JSpinner spin_buscar;
    private javax.swing.JSpinner spin_matricula;
    private javax.swing.JSpinner spin_nota1;
    private javax.swing.JSpinner spin_nota2;
    private javax.swing.JSpinner spin_nota3;
    private javax.swing.JSpinner spin_nota4;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txt_curso;
    private javax.swing.JTextField txt_nome;
    // End of variables declaration//GEN-END:variables

   
    
}
